application: gabipurcarudotcom
version: live
runtime: python
api_version: 1

handlers:
- url: /
  static_files: bundle.html
  upload: bundle.html

- url: /favicon.ico
  static_files: favicon.ico
  upload: .*
  expiration: "1d 0m"
